name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[build]
command = "cargo install worker-build@0.8.5 && worker-build --release --panic-unwind"

[env.dev]
build = { command = "cargo install worker-build@0.8.5 && worker-build --dev --panic-unwind" }

[[durable_objects.bindings]]
name = "DurableObject"
class_name = "Stats"

[[migrations]]
tag = "v1"
new_classes = ["Stats"]

[[routes]]
pattern = "siren.mendutmendut.web.id"
custom_domain = true

[[routes]]
pattern = "investors.spotify.com.siren.mendutmendut.web.id"
custom_domain = true

[vars]
UUID = "7e8fa1ce-47ef-4445-bcad-7470c63fbda1"
PROXYIP = "https://raw.githubusercontent.com/zx-vm/proxyip/refs/heads/main/proxyip.txt"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/zet-v/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/zet-v/Siren/refs/heads/master/web/sub.html"
